export const CREATE_SUPPLIER_DIAGNOSIS = 'CREATE_SUPPLIER_DIAGNOSIS';

export const GET_SUPPLIER_DATA_BY_CODE_SUCCESS = 'GET_SUPPLIER_DATA_BY_CODE_SUCCESS';
export const GET_SUPPLIER_DATA_BY_CODE_ERROR = 'GET_SUPPLIER_DATA_BY_CODE_ERROR';

export const GET_ASSIGNEE_LIST_SUCCESS = 'GET_ASSIGNEE_LIST_SUCCESS';
export const GET_REASON_LIST_SUCCESS = 'GET_REASON_LIST_SUCCESS';
export const GET_MANAGER_DATA_SUCCESS = 'GET_MANAGER_DATA_SUCCESS';
export const GET_ASSIGNEE_LIST_ERROR = 'GET_ASSIGNEE_LIST_ERROR';
export const GET_ASSESSMENT_TYPE_SUCCESS = 'GET_ASSESSMENT_TYPE_SUCCESS';
