export const TRIGGER_NOTIFICATION = 'TRIGGER_NOTIFICATION';
export const DONT_SHOW = 'DONT_SHOW';
export const SHOW_MSG = 'SHOW_MSG';

export const GET_USER_NOTIFICATIONS_UNREAD_COUNT_SUCCESS = 'GET_USER_NOTIFICATIONS_UNREAD_COUNT_SUCCESS';
export const GET_USER_NOTIFICATIONS_UNREAD_COUNT_ERROR = 'GET_USER_NOTIFICATIONS_UNREAD_COUNT_ERROR';
export const GET_USER_NOTIFICATIONS_SUCCESS = 'GET_USER_NOTIFICATIONS_SUCCESS';
export const GET_USER_NOTIFICATIONS_ERROR = 'GET_USER_NOTIFICATIONS_ERROR';
export const MARK_AS_READ_NOTIFICATIONS_ERROR = 'MARK_AS_READ_NOTIFICATIONS_ERROR';
export const SET_INTERVAL_ID_WELCOME = 'SET_INTERVAL_ID_WELCOME';
export const GET_USER_NOTIFICATIONS_ACTIVE = 'GET_USER_NOTIFICATIONS_ACTIVE';

export const GET_DOWNLOAD_SUCCESS = 'GET_DOWNLOAD_SUCCESS';
export const GET_DOWNLOAD_ERROR = 'GET_DOWNLOAD_ERROR';
