export const SET_ASSESS_SECTION = 'SET_ASSESS_SECTION';
export const SET_ASSESS_SUB_SECTION = 'SET_ASSESS_SUB_SECTION';
export const SET_QUESTION_SET = 'SET_QUESTION_SET';
export const SET_QUESTION = 'SET_QUESTION';
export const SET_CR_QUESTION_SET = 'SET_CR_QUESTION_SET';
export const SET_CR_QUESTION = 'SET_CR_QUESTION';

export const SET_LAST_UNANSWERED_QUESTION_URL = 'SET_LAST_UNANSWERED_QUESTION_URL';
export const SET_LAST_UNANSWERED_QUESTION_STATUS = 'SET_LAST_UNANSWERED_QUESTION_STATUS';

export const MEDIA_GET_SUCCESS = 'MEDIA_GET_SUCCESS';
export const MEDIA_GET_ERROR = 'MEDIA_GET_ERROR';
export const MEDIA_UPLOAD_SUCCESS = 'MEDIA_UPLOAD_SUCCESS';
export const MEDIA_UPLOAD_ERROR = 'MEDIA_UPLOAD_ERROR';
